USE [HotelBooking]
GO
/****** Object:  UserDefinedFunction [dbo].[Fn_MinRemain]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Trung
-- Create date: 17/08/2020
-- Description:	Return min remain of RoomType from @CheckInDate to @CheckOutDate
-- =============================================
CREATE FUNCTION [dbo].[Fn_MinRemain]
(
	@RoomTypeId int,
	@CheckInDate DATE,
	@CheckOutDate DATE
)
RETURNS INT
AS
	BEGIN
	DECLARE @tableDate TABLE (
		Dates DATE
	);
	DECLARE @Counter INT, @TotalCount INT
	SET @Counter = 0
	SET @TotalCount = DateDiff(DD,@CheckInDate,@CheckOutDate)
	DECLARE @DateValue DATETIME
	DECLARE @Result INT
	SET @Result = (SELECT Quantity FROM ROOMTYPE WHERE RoomTypeId = @RoomTypeId)
	WHILE (@Counter < @TotalCount)
	BEGIN
		SET  @DateValue= DATEADD(DD,@Counter,@CheckInDate)
		DECLARE @CurrentRemain INT
		SET @CurrentRemain = (SELECT Quantity FROM ROOMTYPE WHERE RoomTypeId = @RoomTypeId) - (SELECT SUM(RoomQuantity) FROM BOOKINGROOMDETAILS WHERE @DateValue = Date AND RoomTypeId = @RoomTypeId)
		IF (@CurrentRemain < @Result)
		BEGIN
			SET @Result = @CurrentRemain
		END
		SET @Counter = @Counter + 1
	END
	RETURN @Result
END
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetRoleClaims]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetRoleClaims](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RoleId] [nvarchar](450) NOT NULL,
	[ClaimType] [nvarchar](max) NULL,
	[ClaimValue] [nvarchar](max) NULL,
 CONSTRAINT [PK_AspNetRoleClaims] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetRoles]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetRoles](
	[Id] [nvarchar](450) NOT NULL,
	[Name] [nvarchar](256) NULL,
	[NormalizedName] [nvarchar](256) NULL,
	[ConcurrencyStamp] [nvarchar](max) NULL,
 CONSTRAINT [PK_AspNetRoles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUserClaims]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserClaims](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [nvarchar](450) NOT NULL,
	[ClaimType] [nvarchar](max) NULL,
	[ClaimValue] [nvarchar](max) NULL,
 CONSTRAINT [PK_AspNetUserClaims] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUserLogins]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserLogins](
	[LoginProvider] [nvarchar](450) NOT NULL,
	[ProviderKey] [nvarchar](450) NOT NULL,
	[ProviderDisplayName] [nvarchar](max) NULL,
	[UserId] [nvarchar](450) NOT NULL,
 CONSTRAINT [PK_AspNetUserLogins] PRIMARY KEY CLUSTERED 
(
	[LoginProvider] ASC,
	[ProviderKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUserRoles]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserRoles](
	[UserId] [nvarchar](450) NOT NULL,
	[RoleId] [nvarchar](450) NOT NULL,
 CONSTRAINT [PK_AspNetUserRoles] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUsers]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUsers](
	[Id] [nvarchar](450) NOT NULL,
	[UserName] [nvarchar](256) NULL,
	[NormalizedUserName] [nvarchar](256) NULL,
	[Email] [nvarchar](256) NULL,
	[NormalizedEmail] [nvarchar](256) NULL,
	[EmailConfirmed] [bit] NOT NULL,
	[PasswordHash] [nvarchar](max) NULL,
	[SecurityStamp] [nvarchar](max) NULL,
	[ConcurrencyStamp] [nvarchar](max) NULL,
	[PhoneNumber] [nvarchar](max) NULL,
	[PhoneNumberConfirmed] [bit] NOT NULL,
	[TwoFactorEnabled] [bit] NOT NULL,
	[LockoutEnd] [datetimeoffset](7) NULL,
	[LockoutEnabled] [bit] NOT NULL,
	[AccessFailedCount] [int] NOT NULL,
	[Name] [nvarchar](30) NOT NULL,
	[Avatar] [nvarchar](max) NULL,
	[Gender] [int] NOT NULL,
	[Address] [nvarchar](max) NULL,
	[IsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_AspNetUsers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUserTokens]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserTokens](
	[UserId] [nvarchar](450) NOT NULL,
	[LoginProvider] [nvarchar](450) NOT NULL,
	[Name] [nvarchar](450) NOT NULL,
	[Value] [nvarchar](max) NULL,
 CONSTRAINT [PK_AspNetUserTokens] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[LoginProvider] ASC,
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BOOKING]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BOOKING](
	[BookingId] [int] IDENTITY(1,1) NOT NULL,
	[CustomerId] [int] NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[CheckinDate] [datetime] NULL,
	[CheckoutDate] [datetime] NULL,
	[NumberofAdults] [int] NULL,
	[NumberofChildren] [int] NULL,
	[ServiceAmount] [float] NULL,
	[RoomAmount] [float] NULL,
	[IsCanceled] [bit] NOT NULL,
	[CouponId] [int] NULL,
 CONSTRAINT [PK_BOOKING] PRIMARY KEY CLUSTERED 
(
	[BookingId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BOOKINGROOMDETAILS]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BOOKINGROOMDETAILS](
	[BookingRoomDetailsId] [int] IDENTITY(1,1) NOT NULL,
	[BookingId] [int] NOT NULL,
	[RoomTypeId] [int] NOT NULL,
	[RoomQuantity] [int] NOT NULL,
	[Date] [datetime] NOT NULL,
	[RoomPrice] [float] NOT NULL,
 CONSTRAINT [PK_BOOKINGROOMDETAILS] PRIMARY KEY CLUSTERED 
(
	[BookingRoomDetailsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BOOKINGSERVICEDETAILS]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BOOKINGSERVICEDETAILS](
	[BookingServiceDetailsId] [int] IDENTITY(1,1) NOT NULL,
	[BookingId] [int] NOT NULL,
	[ServiceId] [int] NOT NULL,
	[ServiceQuantity] [int] NOT NULL,
	[ServicePrice] [float] NOT NULL,
 CONSTRAINT [PK_BOOKINGSERVICEDETAILS] PRIMARY KEY CLUSTERED 
(
	[BookingServiceDetailsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COUPON]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COUPON](
	[CouponId] [int] IDENTITY(1,1) NOT NULL,
	[CouponCode] [nvarchar](50) NOT NULL,
	[Remain] [int] NOT NULL,
	[Reduction] [float] NOT NULL,
	[EndDate] [date] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_COUPON] PRIMARY KEY CLUSTERED 
(
	[CouponId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CUSTOMER]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMER](
	[CustomerId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[PhoneNumber] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[IsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_CUSTOMER] PRIMARY KEY CLUSTERED 
(
	[CustomerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FACILITIES]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FACILITIES](
	[FacilityId] [int] IDENTITY(1,1) NOT NULL,
	[FacilityName] [nvarchar](50) NOT NULL,
	[FacilityImage] [nvarchar](max) NULL,
 CONSTRAINT [PK_FACILITIES] PRIMARY KEY CLUSTERED 
(
	[FacilityId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FACILITIESAPPLY]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FACILITIESAPPLY](
	[FacilitiesApplyId] [int] IDENTITY(1,1) NOT NULL,
	[FacilityId] [int] NOT NULL,
	[RoomTypeId] [int] NOT NULL,
 CONSTRAINT [PK_FACILITIESAPPLY] PRIMARY KEY CLUSTERED 
(
	[FacilitiesApplyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROMOTION]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROMOTION](
	[PromotionId] [int] IDENTITY(1,1) NOT NULL,
	[StartDate] [date] NOT NULL,
	[EndDate] [date] NOT NULL,
	[DiscountRates] [float] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[PromotionName] [nvarchar](50) NULL,
 CONSTRAINT [PK_PROMOTION] PRIMARY KEY CLUSTERED 
(
	[PromotionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROMOTIONAPPLY]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROMOTIONAPPLY](
	[PromotionApplyId] [int] IDENTITY(1,1) NOT NULL,
	[PromotionId] [int] NOT NULL,
	[RoomTypeId] [int] NOT NULL,
 CONSTRAINT [PK_PROMOTIONAPPLY] PRIMARY KEY CLUSTERED 
(
	[PromotionApplyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROOM]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROOM](
	[RoomNumber] [int] NOT NULL,
	[RoomTypeId] [int] NOT NULL,
	[IsOccupied] [bit] NOT NULL,
 CONSTRAINT [PK_ROOM] PRIMARY KEY CLUSTERED 
(
	[RoomNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROOMTYPE]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROOMTYPE](
	[RoomTypeId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[DefaultPrice] [int] NOT NULL,
	[Quantity] [int] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[Description] [nvarchar](max) NULL,
	[MaxAdult] [int] NOT NULL,
	[MaxChildren] [int] NOT NULL,
	[MaxPeople] [int] NOT NULL,
 CONSTRAINT [PK_ROOMTYPE] PRIMARY KEY CLUSTERED 
(
	[RoomTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROOMTYPEIMAGES]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROOMTYPEIMAGES](
	[RoomTypeImageId] [int] IDENTITY(1,1) NOT NULL,
	[ImageData] [nvarchar](max) NOT NULL,
	[RoomTypeId] [int] NOT NULL,
 CONSTRAINT [PK_ROOMTYPEIMAGES] PRIMARY KEY CLUSTERED 
(
	[RoomTypeImageId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SERVICE]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SERVICE](
	[ServiceId] [int] IDENTITY(1,1) NOT NULL,
	[ServiceName] [nvarchar](50) NOT NULL,
	[Price] [int] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[Description] [nvarchar](max) NULL,
 CONSTRAINT [PK_SERVICE] PRIMARY KEY CLUSTERED 
(
	[ServiceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SERVICEIMAGES]    Script Date: 08-03-2023 10:34:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SERVICEIMAGES](
	[ServiceImageId] [int] IDENTITY(1,1) NOT NULL,
	[ImageData] [nvarchar](max) NOT NULL,
	[ServiceId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ServiceImageId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AspNetRoleClaims]  WITH CHECK ADD  CONSTRAINT [FK_AspNetRoleClaims_AspNetRoles_RoleId] FOREIGN KEY([RoleId])
REFERENCES [dbo].[AspNetRoles] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetRoleClaims] CHECK CONSTRAINT [FK_AspNetRoleClaims_AspNetRoles_RoleId]
GO
ALTER TABLE [dbo].[AspNetUserClaims]  WITH CHECK ADD  CONSTRAINT [FK_AspNetUserClaims_AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserClaims] CHECK CONSTRAINT [FK_AspNetUserClaims_AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[AspNetUserLogins]  WITH CHECK ADD  CONSTRAINT [FK_AspNetUserLogins_AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserLogins] CHECK CONSTRAINT [FK_AspNetUserLogins_AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[AspNetUserRoles]  WITH CHECK ADD  CONSTRAINT [FK_AspNetUserRoles_AspNetRoles_RoleId] FOREIGN KEY([RoleId])
REFERENCES [dbo].[AspNetRoles] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserRoles] CHECK CONSTRAINT [FK_AspNetUserRoles_AspNetRoles_RoleId]
GO
ALTER TABLE [dbo].[AspNetUserRoles]  WITH CHECK ADD  CONSTRAINT [FK_AspNetUserRoles_AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserRoles] CHECK CONSTRAINT [FK_AspNetUserRoles_AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[AspNetUserTokens]  WITH CHECK ADD  CONSTRAINT [FK_AspNetUserTokens_AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserTokens] CHECK CONSTRAINT [FK_AspNetUserTokens_AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[BOOKING]  WITH CHECK ADD  CONSTRAINT [FK_BOOKING_COUPON] FOREIGN KEY([CouponId])
REFERENCES [dbo].[COUPON] ([CouponId])
GO
ALTER TABLE [dbo].[BOOKING] CHECK CONSTRAINT [FK_BOOKING_COUPON]
GO
ALTER TABLE [dbo].[BOOKING]  WITH CHECK ADD  CONSTRAINT [FK_BOOKING_CUSTOMER] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[CUSTOMER] ([CustomerId])
GO
ALTER TABLE [dbo].[BOOKING] CHECK CONSTRAINT [FK_BOOKING_CUSTOMER]
GO
ALTER TABLE [dbo].[BOOKINGROOMDETAILS]  WITH CHECK ADD  CONSTRAINT [FK_BOOKINGROOMDETAILS_BOOKING] FOREIGN KEY([BookingId])
REFERENCES [dbo].[BOOKING] ([BookingId])
GO
ALTER TABLE [dbo].[BOOKINGROOMDETAILS] CHECK CONSTRAINT [FK_BOOKINGROOMDETAILS_BOOKING]
GO
ALTER TABLE [dbo].[BOOKINGROOMDETAILS]  WITH CHECK ADD  CONSTRAINT [FK_BOOKINGROOMDETAILS_ROOMTYPE] FOREIGN KEY([RoomTypeId])
REFERENCES [dbo].[ROOMTYPE] ([RoomTypeId])
GO
ALTER TABLE [dbo].[BOOKINGROOMDETAILS] CHECK CONSTRAINT [FK_BOOKINGROOMDETAILS_ROOMTYPE]
GO
ALTER TABLE [dbo].[BOOKINGSERVICEDETAILS]  WITH CHECK ADD  CONSTRAINT [FK_BOOKINGSERVICEDETAILS_BOOKING] FOREIGN KEY([BookingId])
REFERENCES [dbo].[BOOKING] ([BookingId])
GO
ALTER TABLE [dbo].[BOOKINGSERVICEDETAILS] CHECK CONSTRAINT [FK_BOOKINGSERVICEDETAILS_BOOKING]
GO
ALTER TABLE [dbo].[BOOKINGSERVICEDETAILS]  WITH CHECK ADD  CONSTRAINT [FK_BOOKINGSERVICEDETAILS_SERVICE] FOREIGN KEY([ServiceId])
REFERENCES [dbo].[SERVICE] ([ServiceId])
GO
ALTER TABLE [dbo].[BOOKINGSERVICEDETAILS] CHECK CONSTRAINT [FK_BOOKINGSERVICEDETAILS_SERVICE]
GO
ALTER TABLE [dbo].[FACILITIESAPPLY]  WITH CHECK ADD  CONSTRAINT [FK_FACILITIESAPPLY_FACILITIES] FOREIGN KEY([FacilityId])
REFERENCES [dbo].[FACILITIES] ([FacilityId])
GO
ALTER TABLE [dbo].[FACILITIESAPPLY] CHECK CONSTRAINT [FK_FACILITIESAPPLY_FACILITIES]
GO
ALTER TABLE [dbo].[FACILITIESAPPLY]  WITH CHECK ADD  CONSTRAINT [FK_FACILITIESAPPLY_ROOMTYPE] FOREIGN KEY([RoomTypeId])
REFERENCES [dbo].[ROOMTYPE] ([RoomTypeId])
GO
ALTER TABLE [dbo].[FACILITIESAPPLY] CHECK CONSTRAINT [FK_FACILITIESAPPLY_ROOMTYPE]
GO
ALTER TABLE [dbo].[PROMOTIONAPPLY]  WITH CHECK ADD  CONSTRAINT [FK_PROMOTIONAPPLY_PROMOTION] FOREIGN KEY([PromotionId])
REFERENCES [dbo].[PROMOTION] ([PromotionId])
GO
ALTER TABLE [dbo].[PROMOTIONAPPLY] CHECK CONSTRAINT [FK_PROMOTIONAPPLY_PROMOTION]
GO
ALTER TABLE [dbo].[PROMOTIONAPPLY]  WITH CHECK ADD  CONSTRAINT [FK_PROMOTIONAPPLY_ROOMTYPE] FOREIGN KEY([RoomTypeId])
REFERENCES [dbo].[ROOMTYPE] ([RoomTypeId])
GO
ALTER TABLE [dbo].[PROMOTIONAPPLY] CHECK CONSTRAINT [FK_PROMOTIONAPPLY_ROOMTYPE]
GO
ALTER TABLE [dbo].[ROOM]  WITH CHECK ADD  CONSTRAINT [FK_ROOM_ROOMTYPE] FOREIGN KEY([RoomTypeId])
REFERENCES [dbo].[ROOMTYPE] ([RoomTypeId])
GO
ALTER TABLE [dbo].[ROOM] CHECK CONSTRAINT [FK_ROOM_ROOMTYPE]
GO
ALTER TABLE [dbo].[ROOMTYPEIMAGES]  WITH CHECK ADD  CONSTRAINT [FK_ROOMTYPEIMAGES_ROOMTYPE] FOREIGN KEY([RoomTypeId])
REFERENCES [dbo].[ROOMTYPE] ([RoomTypeId])
GO
ALTER TABLE [dbo].[ROOMTYPEIMAGES] CHECK CONSTRAINT [FK_ROOMTYPEIMAGES_ROOMTYPE]
GO
ALTER TABLE [dbo].[SERVICEIMAGES]  WITH CHECK ADD FOREIGN KEY([ServiceId])
REFERENCES [dbo].[SERVICE] ([ServiceId])
GO
ALTER TABLE [dbo].[SERVICEIMAGES]  WITH CHECK ADD FOREIGN KEY([ServiceId])
REFERENCES [dbo].[SERVICE] ([ServiceId])
GO
ALTER TABLE [dbo].[SERVICEIMAGES]  WITH CHECK ADD FOREIGN KEY([ServiceId])
REFERENCES [dbo].[SERVICE] ([ServiceId])
GO
ALTER TABLE [dbo].[SERVICEIMAGES]  WITH CHECK ADD FOREIGN KEY([ServiceId])
REFERENCES [dbo].[SERVICE] ([ServiceId])
GO
ALTER TABLE [dbo].[SERVICEIMAGES]  WITH CHECK ADD FOREIGN KEY([ServiceId])
REFERENCES [dbo].[SERVICE] ([ServiceId])
GO
ALTER TABLE [dbo].[SERVICEIMAGES]  WITH CHECK ADD FOREIGN KEY([ServiceId])
REFERENCES [dbo].[SERVICE] ([ServiceId])
GO
